### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by starwobble** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#10]
Hello fellow user, I heard VaporousCreeper was banned on someserver. 
I was wondering if you could unban him and set the record straight for us?

Anyways brb as usual.

~ Lildoughnut owo

**Comment by BradF-99** [comment]
If you have a rigged random number generator that can roll a 1, but make it look "natural", that would be splendid.

**Comment by starwobble** [comment]
Sounds like a good idea... hopefully lasermatic can make one.
