### ISSUE TITLE
Newbie coder, would like to figure out a simple RNG code!

### ISSUE THREAD

**Issue by Lasermatic** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#12]
Hello, VaporousCreeper! 😃 

I'm new to coding, and would love to create a short but effective random number generator within a range of 1 to 1000000. I do not require anything fancy, just want to learn how to actually output a random number and a counter for each roll.

If possible, I'd like to learn how to read the outputted number and save the lowest and highest number created with each more. Furthermore, how to overwrite said saved number so I am left with the highest and lowest number created by roll.

Thank you for reading, I would be most grateful for your most rapid and detailed response.
Cheers, Laser ❤️

**Comment by starwobble** [comment]
I LVOE IT XD

**Comment by Lasermatic** [comment]
> 
> 
> I LVOE IT XD

I am so glad you love my request, I have been eagerly awaiting a response from VaporousCreeper, it feels good to know the fans are out there waiting too!

Much love, Laser ❤️

**Comment by starwobble** [comment]
> > I LVOE IT XD
> 
> I am so glad you love my request, I have been eagerly awaiting a response from VaporousCreeper, it feels good to know the fans are out there waiting too!
> 
> Much love, Laser ❤️

my bones and feelings feel so good after this.. i cannot hold my self together with joy and excitement from this reply.. god bless

**Comment by starwobble** [comment]
[](https://cdn.discordapp.com/emojis/463636331940282368.png) sorry forgot pic ;)

**Comment by starwobble** [comment]
https://cdn.discordapp.com/emojis/463636331940282368.png

**Comment by starwobble** [comment]
here link open

**Comment by BradF-99** [comment]
Hi @Lasermatic ,

I am not @VaporousCreeper but hopefully this will help you.

In order to make random unsigned integers we can use an algorithm known as the Mersenne Twister. It's a Pseudo-random Number Generator and it's the most used by far. This is an example of one which has been created by Github user ESultanik.

```
inline void m_seedRand(MTRand* rand, unsigned long seed) {
  /* set initial seeds to mt[STATE_VECTOR_LENGTH] using the generator
   * from Line 25 of Table 1 in: Donald Knuth, "The Art of Computer
   * Programming," Vol. 2 (2nd Ed.) pp.102.
   */
  rand->mt[0] = seed & 0xffffffff;
  for(rand->index=1; rand->index<STATE_VECTOR_LENGTH; rand->index++) {
    rand->mt[rand->index] = (6069 * rand->mt[rand->index-1]) & 0xffffffff;
  }
}

/**
* Creates a new random number generator from a given seed.
*/
MTRand seedRand(unsigned long seed) {
  MTRand rand;
  m_seedRand(&rand, seed);
  return rand;
}

/**
 * Generates a pseudo-randomly generated long.
 */
unsigned long genRandLong(MTRand* rand) {

  unsigned long y;
  static unsigned long mag[2] = {0x0, 0x9908b0df}; /* mag[x] = x * 0x9908b0df for x = 0,1 */
  if(rand->index >= STATE_VECTOR_LENGTH || rand->index < 0) {
    /* generate STATE_VECTOR_LENGTH words at a time */
    int kk;
    if(rand->index >= STATE_VECTOR_LENGTH+1 || rand->index < 0) {
      m_seedRand(rand, 4357);
    }
    for(kk=0; kk<STATE_VECTOR_LENGTH-STATE_VECTOR_M; kk++) {
      y = (rand->mt[kk] & UPPER_MASK) | (rand->mt[kk+1] & LOWER_MASK);
      rand->mt[kk] = rand->mt[kk+STATE_VECTOR_M] ^ (y >> 1) ^ mag[y & 0x1];
    }
    for(; kk<STATE_VECTOR_LENGTH-1; kk++) {
      y = (rand->mt[kk] & UPPER_MASK) | (rand->mt[kk+1] & LOWER_MASK);
      rand->mt[kk] = rand->mt[kk+(STATE_VECTOR_M-STATE_VECTOR_LENGTH)] ^ (y >> 1) ^ mag[y & 0x1];
    }
    y = (rand->mt[STATE_VECTOR_LENGTH-1] & UPPER_MASK) | (rand->mt[0] & LOWER_MASK);
    rand->mt[STATE_VECTOR_LENGTH-1] = rand->mt[STATE_VECTOR_M-1] ^ (y >> 1) ^ mag[y & 0x1];
    rand->index = 0;
  }
  y = rand->mt[rand->index++];
  y ^= (y >> 11);
  y ^= (y << 7) & TEMPERING_MASK_B;
  y ^= (y << 15) & TEMPERING_MASK_C;
  y ^= (y >> 18);
  return y;
}

/**
 * Generates a pseudo-randomly generated double in the range [0..1].
 */
double genRand(MTRand* rand) {
  return((double)genRandLong(rand) / (unsigned long)0xffffffff);
}

```

Hopefully this helps.

Kind regards

**Comment by starwobble** [comment]
Garry's Mod  is a sandbox physics game developed by Facepunch Studios and published by Valve Corporation. Garry's Mod was originally a mod created by Garry Newman for Valve Corporation's Half-Life 2 but was later made into a standalone release on 29 November 2006 for Microsoft Windows. Later updates saw an OS X port, added in 2010, and a version for Linux in 2013.
Gameplay  
The base game mode "sandbox" has no set objectives, and gives the player the freedom to spawn non-player characters, ragdolls or objects, such as furniture, shipping containers, dumpsters and explosions, and interact with them in various ways.
A variety of props, NPCs, and ragdolls can be selected and placed into the sandbox from any installed game running on the Source game engine or from the community-created collections, such as PHX3 for props and Civil Protection model packs for ragdolls. An important tool offered to the player, the Physics Gun, allows the props and ragdolls to be picked up, rotated, and frozen in place. Another important implement, the Tool Gun, is a multi-purpose tool for performing various tasks, such as constraining props together, creating interactive buttons, and creating controllable winches and wheels. It can also be used to change the facial expression and pose the digits of a ragdoll. The Tool Gun can also be used to control and use add-ons created by the community, which can be accessed through the Steam Workshop.
The game uses the Source engine's modified version of the Havok physics engine, which allows players to build contraptions that follow the laws of physics, allowing realistic simulations of structures and experiments.
User-created content  
Garry's Mod allows users to take advantage of the extensibility of the Source Engine through the spawn menu which enables users to spawn models and maps imported by the user. Since Garry's Mod version 9, Lua scripting has been a notable feature added to the game which allows players to run their own scripts, which expanded potential user modifications by enabling the creation of scripted weapons, entities, vehicles, tools, game modes and NPCs that weren't possible in the game before. Multiplayer game servers will automatically attempt to send any custom content to the client when they connect. Most users prefer to download the Server Data from the Steam Workshop. Examples include game modes such as Trouble in Terrorist Town, DarkRP, Deathrun, Jailbreak, Prop Hunt, and Murder.
Wiremod   
Wiremod is a user-created mod that significantly expands the sandbox capabilities of the game by adding a large number of pseudo-electronic components such as microcontrollers, logic gates, buttons, radios, gyroscopes, screens, GPS modules, sensors, laser rangefinders, speed sensors and much more. Wiring these components together allows the player to create a very large variety of electronically-controlled machines. It also features Expression2  general-purpose controllers, which allow the player to program the chip with a high-level programming language to compute inputs and outputs to control a wide swathe of elements. CPU modules, which use a Low-level programming language, allow similar capabilities, as well as the capability to render graphics on a digital screen, to be able to fully simulate a virtual computer. The use of Wiremod allows the creation of very complex contraptions, and everything from virtual computers to missiles, aircraft, spaceships and space probes, robots and drones; all constructed from components available in-game without the use of modded entities.
Fretta contest   
In winter 2009–2010, a contest was held for Garry's Mod by the game's developers to create the best new game mode using a programming framework called "Fretta". Fretta, Italian for "hurry", allows developers to quickly and easily create new game modes for Garry's Mod with commonly required functionality already implemented so the developers can focus on unique aspects of their game modes. Fretta was inspired by a similar fan-created framework "Rambo_6's Simple Gamemode Base". However, for inclusion in Garry's Mod, Newman decided to rewrite it with input and contributions from the original author and other developers. The winners of the contest range from a recreation of the Mafia party game to an aerial combat game

**Comment by starwobble** [comment]
HELP I GOT TYPO I CANT FIND IT

**Comment by Lasermatic** [comment]
> 
> 
> > > I LVOE IT XD
> > 
> > 
> > I am so glad you love my request, I have been eagerly awaiting a response from VaporousCreeper, it feels good to know the fans are out there waiting too!
> > Much love, Laser ❤️
> 
> my bones and feelings feel so good after this.. i cannot hold my self together with joy and excitement from this reply.. god bless



> 
> 
> sorry forgot pic ;)



> 
> 
> https://cdn.discordapp.com/emojis/463636331940282368.png



> 
> 
> here link open

Goodness, I'm blushing! 😊 
It feels so good to be part of the VaporousCreeper GitHub Community! 



> 
> 
> Hi @Lasermatic ,
> 
> I am not @VaporousCreeper but hopefully this will help you.
> 
> In order to make random unsigned integers we can use an algorithm known as the Mersenne Twister. It's a Pseudo-random Number Generator and it's the most used by far. This is an example of one which has been created by Github user ESultanik.
> 
> ```
> inline void m_seedRand(MTRand* rand, unsigned long seed) {
>   /* set initial seeds to mt[STATE_VECTOR_LENGTH] using the generator
>    * from Line 25 of Table 1 in: Donald Knuth, "The Art of Computer
>    * Programming," Vol. 2 (2nd Ed.) pp.102.
>    */
>   rand->mt[0] = seed & 0xffffffff;
>   for(rand->index=1; rand->index<STATE_VECTOR_LENGTH; rand->index++) {
>     rand->mt[rand->index] = (6069 * rand->mt[rand->index-1]) & 0xffffffff;
>   }
> }
> 
> /**
> * Creates a new random number generator from a given seed.
> */
> MTRand seedRand(unsigned long seed) {
>   MTRand rand;
>   m_seedRand(&rand, seed);
>   return rand;
> }
> 
> /**
>  * Generates a pseudo-randomly generated long.
>  */
> unsigned long genRandLong(MTRand* rand) {
> 
>   unsigned long y;
>   static unsigned long mag[2] = {0x0, 0x9908b0df}; /* mag[x] = x * 0x9908b0df for x = 0,1 */
>   if(rand->index >= STATE_VECTOR_LENGTH || rand->index < 0) {
>     /* generate STATE_VECTOR_LENGTH words at a time */
>     int kk;
>     if(rand->index >= STATE_VECTOR_LENGTH+1 || rand->index < 0) {
>       m_seedRand(rand, 4357);
>     }
>     for(kk=0; kk<STATE_VECTOR_LENGTH-STATE_VECTOR_M; kk++) {
>       y = (rand->mt[kk] & UPPER_MASK) | (rand->mt[kk+1] & LOWER_MASK);
>       rand->mt[kk] = rand->mt[kk+STATE_VECTOR_M] ^ (y >> 1) ^ mag[y & 0x1];
>     }
>     for(; kk<STATE_VECTOR_LENGTH-1; kk++) {
>       y = (rand->mt[kk] & UPPER_MASK) | (rand->mt[kk+1] & LOWER_MASK);
>       rand->mt[kk] = rand->mt[kk+(STATE_VECTOR_M-STATE_VECTOR_LENGTH)] ^ (y >> 1) ^ mag[y & 0x1];
>     }
>     y = (rand->mt[STATE_VECTOR_LENGTH-1] & UPPER_MASK) | (rand->mt[0] & LOWER_MASK);
>     rand->mt[STATE_VECTOR_LENGTH-1] = rand->mt[STATE_VECTOR_M-1] ^ (y >> 1) ^ mag[y & 0x1];
>     rand->index = 0;
>   }
>   y = rand->mt[rand->index++];
>   y ^= (y >> 11);
>   y ^= (y << 7) & TEMPERING_MASK_B;
>   y ^= (y << 15) & TEMPERING_MASK_C;
>   y ^= (y >> 18);
>   return y;
> }
> 
> /**
>  * Generates a pseudo-randomly generated double in the range [0..1].
>  */
> double genRand(MTRand* rand) {
>   return((double)genRandLong(rand) / (unsigned long)0xffffffff);
> }
> ```
> 
> Hopefully this helps.
> 
> Kind regards

Thank you @BradF-99, this is so interesting and insightful! 😂 
I am highly gracious of your kind input. I have created the RNG and now streaming it on Twitch for my friends to watch to see if it outputs a "1" out of 1,000,000 !!! 🤣 



> 
> 
> Garry's Mod is a sandbox physics game developed by Facepunch Studios and published by Valve Corporation. Garry's Mod was originally a mod created by Garry Newman for Valve Corporation's Half-Life 2 but was later made into a standalone release on 29 November 2006 for Microsoft Windows. Later updates saw an OS X port, added in 2010, and a version for Linux in 2013.
> Gameplay
> The base game mode "sandbox" has no set objectives, and gives the player the freedom to spawn non-player characters, ragdolls or objects, such as furniture, shipping containers, dumpsters and explosions, and interact with them in various ways.
> A variety of props, NPCs, and ragdolls can be selected and placed into the sandbox from any installed game running on the Source game engine or from the community-created collections, such as PHX3 for props and Civil Protection model packs for ragdolls. An important tool offered to the player, the Physics Gun, allows the props and ragdolls to be picked up, rotated, and frozen in place. Another important implement, the Tool Gun, is a multi-purpose tool for performing various tasks, such as constraining props together, creating interactive buttons, and creating controllable winches and wheels. It can also be used to change the facial expression and pose the digits of a ragdoll. The Tool Gun can also be used to control and use add-ons created by the community, which can be accessed through the Steam Workshop.
> The game uses the Source engine's modified version of the Havok physics engine, which allows players to build contraptions that follow the laws of physics, allowing realistic simulations of structures and experiments.
> User-created content
> Garry's Mod allows users to take advantage of the extensibility of the Source Engine through the spawn menu which enables users to spawn models and maps imported by the user. Since Garry's Mod version 9, Lua scripting has been a notable feature added to the game which allows players to run their own scripts, which expanded potential user modifications by enabling the creation of scripted weapons, entities, vehicles, tools, game modes and NPCs that weren't possible in the game before. Multiplayer game servers will automatically attempt to send any custom content to the client when they connect. Most users prefer to download the Server Data from the Steam Workshop. Examples include game modes such as Trouble in Terrorist Town, DarkRP, Deathrun, Jailbreak, Prop Hunt, and Murder.
> Wiremod
> Wiremod is a user-created mod that significantly expands the sandbox capabilities of the game by adding a large number of pseudo-electronic components such as microcontrollers, logic gates, buttons, radios, gyroscopes, screens, GPS modules, sensors, laser rangefinders, speed sensors and much more. Wiring these components together allows the player to create a very large variety of electronically-controlled machines. It also features Expression2 general-purpose controllers, which allow the player to program the chip with a high-level programming language to compute inputs and outputs to control a wide swathe of elements. CPU modules, which use a Low-level programming language, allow similar capabilities, as well as the capability to render graphics on a digital screen, to be able to fully simulate a virtual computer. The use of Wiremod allows the creation of very complex contraptions, and everything from virtual computers to missiles, aircraft, spaceships and space probes, robots and drones; all constructed from components available in-game without the use of modded entities.
> Fretta contest
> In winter 2009–2010, a contest was held for Garry's Mod by the game's developers to create the best new game mode using a programming framework called "Fretta". Fretta, Italian for "hurry", allows developers to quickly and easily create new game modes for Garry's Mod with commonly required functionality already implemented so the developers can focus on unique aspects of their game modes. Fretta was inspired by a similar fan-created framework "Rambo_6's Simple Gamemode Base". However, for inclusion in Garry's Mod, Newman decided to rewrite it with input and contributions from the original author and other developers. The winners of the contest range from a recreation of the Mafia party game to an aerial combat game

This is very interesting, I'd sure love to learn more !!! 🤓 ❤️ 



> 
> 
> HELP I GOT TYPO I CANT FIND IT

Oh boy! That's alright, it's the acknowledging the mistakes rather than pointing them out that matters!
Stay positive 😄 ❤️

**Comment by starwobble** [comment]
@VaporousCreeper thanks for replying on my issue !!!!

**Comment by starwobble** [comment]
wait nvm wrong person

**Comment by starwobble** [comment]
wait wrong issue

**Comment by starwobble** [comment]
sorry guys

**Comment by starwobble** [comment]
not spamming

**Comment by starwobble** [comment]
anyways gotta brb

**Comment by Lasermatic** [comment]
> 
> 
> > > > I LVOE IT XD
> > > 
> > > 
> > > I am so glad you love my request, I have been eagerly awaiting a response from VaporousCreeper, it feels good to know the fans are out there waiting too!
> > > Much love, Laser ❤️
> > 
> > 
> > my bones and feelings feel so good after this.. i cannot hold my self together with joy and excitement from this reply.. god bless
> 
> > sorry forgot pic ;)
> 
> > https://cdn.discordapp.com/emojis/463636331940282368.png
> 
> > here link open
> 
> Goodness, I'm blushing! 😊
> It feels so good to be part of the VaporousCreeper GitHub Community!
> 
> > Hi @Lasermatic ,
> > I am not @VaporousCreeper but hopefully this will help you.
> > In order to make random unsigned integers we can use an algorithm known as the Mersenne Twister. It's a Pseudo-random Number Generator and it's the most used by far. This is an example of one which has been created by Github user ESultanik.
> > ```
> > inline void m_seedRand(MTRand* rand, unsigned long seed) {
> >   /* set initial seeds to mt[STATE_VECTOR_LENGTH] using the generator
> >    * from Line 25 of Table 1 in: Donald Knuth, "The Art of Computer
> >    * Programming," Vol. 2 (2nd Ed.) pp.102.
> >    */
> >   rand->mt[0] = seed & 0xffffffff;
> >   for(rand->index=1; rand->index<STATE_VECTOR_LENGTH; rand->index++) {
> >     rand->mt[rand->index] = (6069 * rand->mt[rand->index-1]) & 0xffffffff;
> >   }
> > }
> > 
> > /**
> > * Creates a new random number generator from a given seed.
> > */
> > MTRand seedRand(unsigned long seed) {
> >   MTRand rand;
> >   m_seedRand(&rand, seed);
> >   return rand;
> > }
> > 
> > /**
> >  * Generates a pseudo-randomly generated long.
> >  */
> > unsigned long genRandLong(MTRand* rand) {
> > 
> >   unsigned long y;
> >   static unsigned long mag[2] = {0x0, 0x9908b0df}; /* mag[x] = x * 0x9908b0df for x = 0,1 */
> >   if(rand->index >= STATE_VECTOR_LENGTH || rand->index < 0) {
> >     /* generate STATE_VECTOR_LENGTH words at a time */
> >     int kk;
> >     if(rand->index >= STATE_VECTOR_LENGTH+1 || rand->index < 0) {
> >       m_seedRand(rand, 4357);
> >     }
> >     for(kk=0; kk<STATE_VECTOR_LENGTH-STATE_VECTOR_M; kk++) {
> >       y = (rand->mt[kk] & UPPER_MASK) | (rand->mt[kk+1] & LOWER_MASK);
> >       rand->mt[kk] = rand->mt[kk+STATE_VECTOR_M] ^ (y >> 1) ^ mag[y & 0x1];
> >     }
> >     for(; kk<STATE_VECTOR_LENGTH-1; kk++) {
> >       y = (rand->mt[kk] & UPPER_MASK) | (rand->mt[kk+1] & LOWER_MASK);
> >       rand->mt[kk] = rand->mt[kk+(STATE_VECTOR_M-STATE_VECTOR_LENGTH)] ^ (y >> 1) ^ mag[y & 0x1];
> >     }
> >     y = (rand->mt[STATE_VECTOR_LENGTH-1] & UPPER_MASK) | (rand->mt[0] & LOWER_MASK);
> >     rand->mt[STATE_VECTOR_LENGTH-1] = rand->mt[STATE_VECTOR_M-1] ^ (y >> 1) ^ mag[y & 0x1];
> >     rand->index = 0;
> >   }
> >   y = rand->mt[rand->index++];
> >   y ^= (y >> 11);
> >   y ^= (y << 7) & TEMPERING_MASK_B;
> >   y ^= (y << 15) & TEMPERING_MASK_C;
> >   y ^= (y >> 18);
> >   return y;
> > }
> > 
> > /**
> >  * Generates a pseudo-randomly generated double in the range [0..1].
> >  */
> > double genRand(MTRand* rand) {
> >   return((double)genRandLong(rand) / (unsigned long)0xffffffff);
> > }
> > ```
> > Hopefully this helps.
> > Kind regards
> 
> Thank you @BradF-99, this is so interesting and insightful! 😂
> I am highly gracious of your kind input. I have created the RNG and now streaming it on Twitch for my friends to watch to see if it outputs a "1" out of 1,000,000 !!! 🤣
> 
> > Garry's Mod is a sandbox physics game developed by Facepunch Studios and published by Valve Corporation. Garry's Mod was originally a mod created by Garry Newman for Valve Corporation's Half-Life 2 but was later made into a standalone release on 29 November 2006 for Microsoft Windows. Later updates saw an OS X port, added in 2010, and a version for Linux in 2013.
> > Gameplay
> > The base game mode "sandbox" has no set objectives, and gives the player the freedom to spawn non-player characters, ragdolls or objects, such as furniture, shipping containers, dumpsters and explosions, and interact with them in various ways.
> > A variety of props, NPCs, and ragdolls can be selected and placed into the sandbox from any installed game running on the Source game engine or from the community-created collections, such as PHX3 for props and Civil Protection model packs for ragdolls. An important tool offered to the player, the Physics Gun, allows the props and ragdolls to be picked up, rotated, and frozen in place. Another important implement, the Tool Gun, is a multi-purpose tool for performing various tasks, such as constraining props together, creating interactive buttons, and creating controllable winches and wheels. It can also be used to change the facial expression and pose the digits of a ragdoll. The Tool Gun can also be used to control and use add-ons created by the community, which can be accessed through the Steam Workshop.
> > The game uses the Source engine's modified version of the Havok physics engine, which allows players to build contraptions that follow the laws of physics, allowing realistic simulations of structures and experiments.
> > User-created content
> > Garry's Mod allows users to take advantage of the extensibility of the Source Engine through the spawn menu which enables users to spawn models and maps imported by the user. Since Garry's Mod version 9, Lua scripting has been a notable feature added to the game which allows players to run their own scripts, which expanded potential user modifications by enabling the creation of scripted weapons, entities, vehicles, tools, game modes and NPCs that weren't possible in the game before. Multiplayer game servers will automatically attempt to send any custom content to the client when they connect. Most users prefer to download the Server Data from the Steam Workshop. Examples include game modes such as Trouble in Terrorist Town, DarkRP, Deathrun, Jailbreak, Prop Hunt, and Murder.
> > Wiremod
> > Wiremod is a user-created mod that significantly expands the sandbox capabilities of the game by adding a large number of pseudo-electronic components such as microcontrollers, logic gates, buttons, radios, gyroscopes, screens, GPS modules, sensors, laser rangefinders, speed sensors and much more. Wiring these components together allows the player to create a very large variety of electronically-controlled machines. It also features Expression2 general-purpose controllers, which allow the player to program the chip with a high-level programming language to compute inputs and outputs to control a wide swathe of elements. CPU modules, which use a Low-level programming language, allow similar capabilities, as well as the capability to render graphics on a digital screen, to be able to fully simulate a virtual computer. The use of Wiremod allows the creation of very complex contraptions, and everything from virtual computers to missiles, aircraft, spaceships and space probes, robots and drones; all constructed from components available in-game without the use of modded entities.
> > Fretta contest
> > In winter 2009–2010, a contest was held for Garry's Mod by the game's developers to create the best new game mode using a programming framework called "Fretta". Fretta, Italian for "hurry", allows developers to quickly and easily create new game modes for Garry's Mod with commonly required functionality already implemented so the developers can focus on unique aspects of their game modes. Fretta was inspired by a similar fan-created framework "Rambo_6's Simple Gamemode Base". However, for inclusion in Garry's Mod, Newman decided to rewrite it with input and contributions from the original author and other developers. The winners of the contest range from a recreation of the Mafia party game to an aerial combat game
> 
> This is very interesting, I'd sure love to learn more !!! 🤓 ❤️
> 
> > HELP I GOT TYPO I CANT FIND IT
> 
> Oh boy! That's alright, it's the acknowledging the mistakes rather than pointing them out that matters!
> Stay positive 😄 ❤️



> 
> 
> @VaporousCreeper thanks for replying on my issue !!!!

Sorry, @VaporousCreeper! @starwobble accidentally posted this thinking I was you. 
Humble regards, @Lasermatic ❤️ 


> 
> 
> wait nvm wrong person

That's okay, I told @VaporousCreeper that you were mistaken. 😄 



> 
> 
> wait wrong issue

Oh that's okay, we all make mistakes! 😂


> 
> 
> sorry guys

No need to say sorry, you're all good here, mate! 👍 


> 
> 
> not spamming

Oh I know, I understand. 😔 


> 
> 
> anyways gotta brb

See you soon! 👋

**Comment by Lasermatic** [comment]
Whoops, I accidentally quoted my last post. I am so sorry, much apologies. 😸

**Comment by Lasermatic** [comment]
Sorry again, I meant "my apologies". Must be a lack of sleep from waiting on your response. 😂

**Comment by Lasermatic** [comment]
> 
> 
> Whoops, I accidentally quoted my last post. I am so sorry, much apologies. 😸



> 
> 
> Sorry again, I meant "my apologies". Must be a lack of sleep from waiting on your response. 😂

I am so terribly sorry, I wanted to quote my mistake in my latest post. I accidentally sent it by accident. 

Accident.
💯

**Comment by BradF-99** [comment]
> 
> 
> > Whoops, I accidentally quoted my last post. I am so sorry, much apologies. 😸
> 
> > Sorry again, I meant "my apologies". Must be a lack of sleep from waiting on your response. 😂
> 
> I am so terribly sorry, I wanted to quote my mistake in my latest post. I accidentally sent it by accident.
> 
> Accident.
> 💯

This is quite OK! 😸 As you said before yourself, we all make mistakes from time to time. Hopefully @VaporousCreeper will be able to respond soon to assist with your query.

Kind regards

**Comment by starwobble** [comment]
HELLO I FORGOT TO REPLY
