### ISSUE TITLE
ISSUE #383271

### ISSUE THREAD

**Issue by starwobble** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#13]
Noticed some bad things happening with repo??? the issues keep going away but no fix??

ETA

thanks

**Comment by VaporousCreeper** [comment]
Because those issues are Irrelevant for the repo. 
This repo is meant for BetterDiscord Theme and plugins that people can grap and use, not to request a ban appeal on some discord server

Thanks

**Comment by starwobble** [comment]
no u
