### ISSUE TITLE
the background doesn't fully load 

### ISSUE THREAD

**Issue by Benji0w0** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#41]
![image](https://user-images.githubusercontent.com/48769038/54707593-c44f4e80-4b41-11e9-8a61-1b37339010c8.png)
 I reseted everything and for some reason it just doesn't wanna work ;w; I would love it to work but for some reason it just doesn't wanna work but anyway thx for your time :D

**Comment by VaporousCreeper** [comment]
That was most likely from the Transparency2 module from Ruben breaking after a discord update.
Is it still Happening?

**Comment by VaporousCreeper** [comment]
**Issue Resolved**
Issue was Resolved by the user re-installing BetterDiscord
