### ISSUE TITLE
GGO Kirito - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by FauIt** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#42]
### Transparency Error ### 
The theme is really good. But the top bar and some features aren't transparent as shown, maybe a little broken over here? 

![2](https://user-images.githubusercontent.com/49928896/56817020-446e7f80-6877-11e9-8434-8d77bf028e16.PNG)
![3](https://user-images.githubusercontent.com/49928896/56817083-6831c580-6877-11e9-9c25-7a1c875233ab.PNG)
![4](https://user-images.githubusercontent.com/49928896/56817118-7ed81c80-6877-11e9-9a0b-409455fc3bfb.PNG)

**Comment by VaporousCreeper** [comment]
I'm already fixing the source of the theme **GGO Kirito** and I'll close this issue when it's fixed

Thanks

**Comment by FauIt** [comment]
> I'm already fixing the source of the theme **GGO Kirito** and I'll close this issue when it's fixed
> 
> Thanks

Thank you! 👍

**Comment by VaporousCreeper** [comment]
**Resolved**
The issue was fixed by the theme requiring an update

**Update details:** https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/commit/45f8ee1eef9f2d7a86e73e85751cdeba4a23f394
