### ISSUE TITLE
GGO Kirito - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by wolfnightmare** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#55]
hello I would like to report this theme because it does not work on my discord I try more than i wast led but nothing happens

**Comment by VaporousCreeper** [comment]
@wolfnightmare,
I'm going to ask some questions on your discord.

When did you last updated discord?
What is your BD (BetterDiscord) and BBD (Bandaged BetterDiscord) versions?

And also can you provide a picture of this issue because just that won't help me to identify your current issue.

**Comment by Voroshil695** [comment]
Good morning! I have problem with theme. At startup theme , the background is not displayed. Discord was update to the new version.
https://user-images.githubusercontent.com/120298599/230405672-f94998f4-666b-4c5a-96b3-e0be32467593.png
