### ISSUE TITLE
new canary and stable change by discord, causing issues!

### ISSUE THREAD

**Issue by gamerdezade** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#64]
So i use the GGO Kirto theme, its the best out there, my personal favourite. But recently, Discord has pushed out a large change to both Canary and Stable. Which has been glitching the theme, it isn't working like its supposed to, I just wanted to request you to, find the time and come up with update, which resolves these issues, please look into this, as many of us love your theme!
thanks for your work and time!

(i will attach a screenshot showing the issues)
![image](https://user-images.githubusercontent.com/97515609/148923053-f2b676d4-85c7-4288-9550-011aea3e4dac.png)

**Comment by VaporousCreeper** [comment]
Hello gamerdezade,

Thanks for bring the issue to my attention.

I know I rarely work on the theme mainly being that I work full-time and not having enough time.

I'll work on it very shortly.

Kind Regards,
VaporousCreeper.

**Comment by VaporousCreeper** [comment]
Hello gamerdezade,

Fixed the issue. Here's the commit: [d7421e9](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/commit/d7421e9e27866562b5dbb9540482c420dcac328e)

Kind Regards
VaporousCreeper.
