### ISSUE TITLE
Bring back the old looking

### ISSUE THREAD

**Issue by JustSomeRandomGuy3** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#65]
This v1.2.4 even though that you fixed the transparent, it didn't look ANYTHING like the old version. It's just Discord UI.

This is what it have to looks like:
![image](https://user-images.githubusercontent.com/102457568/161416134-e48dc4f6-b5d5-4c7d-9252-b51bc4715446.png)

And this is version 1.2.4:
![image](https://user-images.githubusercontent.com/102457568/161416154-4df28f2d-3540-4024-8b59-123674e37875.png)

This is my favorite theme so hope you fix it!

**Comment by VaporousCreeper** [comment]
Hi,

Sadly I don't have the time to update/maintain the them that I used to have when I made the theme.

I'll try my best to get it in time within around 2 weeks. 

Thanks

**Comment by JustSomeRandomGuy3** [comment]
Hey VapourousCrepper,
It's been a year since this issue created. Is it done yet?

**Comment by VaporousCreeper** [comment]
Hi,

I'm still working on it, It's just very slow at the moment due to me not having enough time and lack of motivation.

It will be done at some point. This issue will be closed as soon as I push an update.

Thanks

**Comment by VaporousCreeper** [comment]
Hi,

Update is now complete, please wait will raw.githack get's the raw file from this Repo.

Thanks.

Update Commit: [ac7162b](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/commit/ac7162bccc63d56cee3f87c7a1f575d41656917e)
