### ISSUE TITLE
Problem with background.

### ISSUE THREAD

**Issue by Voroshil695** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#69]
Hi! I have problem with the theme. When startup theme, background is not displayed. Discord and DiscordBetter were update to the new version.
https://user-images.githubusercontent.com/120298599/230613721-78b0475d-a47e-4894-a1f8-128f14a522df.png
This is screenshot with the problem.

**Comment by JustSomeRandomGuy3** [comment]
Uh? Mine is fine.
![image](https://user-images.githubusercontent.com/102457568/230726983-5dc7e827-521f-4536-bc8a-119543448c07.png)

**Comment by Voroshil695** [comment]
Hmm..strange. Perhaps,  I need change any settings in  DiscordBetter.

**Comment by VaporousCreeper** [comment]
Hi, 

I'm still in the process of updating the theme at the moment. mainly the selectors are just out of date.

Thanks

**Comment by VaporousCreeper** [comment]
Also, The reason you might not see the background image is due the request for the image has failed somehow because the image for the theme comes from this Repo. It should sort it self out. 

I'll close this issue as soon I've pushed an update.

Thanks
