### ISSUE TITLE
problem with background

### ISSUE THREAD

**Issue by niceeeeeeeeeeeeeeeeeeeee** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#74]
the normal background is working as well as the purple but the cyan one doesnt

**Comment by niceeeeeeeeeeeeeeeeeeeee** [comment]
![Themes _ User Settings - Discord 2023  08  26  9_41_47](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/assets/143252588/e40ea2bd-2df9-4a3c-b26e-846c10ec97c4)
#
![Themes _ User Settings - Discord 2023  08  26  9_42_46](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/assets/143252588/567f6c4d-f0f8-4655-831b-c7a7baee43dd)
![Themes _ User Settings - Discord 2023  08  26  9_43_17](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/assets/143252588/b92a061f-bd05-4e53-8943-11c2dac16400)

**Comment by VaporousCreeper** [comment]
Hi,

Try opening the background image url under `--background` variable in the `:root` section on a new web browser tab to see if something is blocking the image. 

Reason being, the images for said themes are not from Github and are out sourced from other websites. I'm also using the Cyan preset and it's working for me so this issue is on your end.

Thanks

**Comment by niceeeeeeeeeeeeeeeeeeeee** [comment]
it says "token validation failed"

**Comment by VaporousCreeper** [comment]
Hi,

Try changing the '--background' variable to 'https://raw.githubusercontent.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/master/Themes/GGO_Kirito/templates/just_kirito_cyan/d89fx8r-b9fb47e8-c2fb-4b62-8bd4-948e015795dc.jpg'. This will determine if the website is blocking you access.

If that fixes it, download the image and save it somewhere else. I'll most likely delete the image from this repository. 

Thanks.

**Comment by niceeeeeeeeeeeeeeeeeeeee** [comment]
it works now thx

**Comment by VaporousCreeper** [comment]
Hi,

I'm glad that the website is at fault.

Like i said before. Save the background image somewhere, I'll be deleting the image from this repository in about 12 to 24 hours.

Thanks,

**Comment by VaporousCreeper** [comment]
Hi, 

I got a feeling you've played around with the token on the url from before. Paste the following url back into the url function. A slight letter change in the token will result in the website refusing access.

Background Image: [Image](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/cb89700e-36e2-43be-a163-58f09df5511f/d89fx8r-b9fb47e8-c2fb-4b62-8bd4-948e015795dc.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2NiODk3MDBlLTM2ZTItNDNiZS1hMTYzLTU4ZjA5ZGY1NTExZlwvZDg5Zng4ci1iOWZiNDdlOC1jMmZiLTRiNjItOGJkNC05NDhlMDE1Nzk1ZGMuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.gC07VheL4HFIchfS7gfFGDfo0nZPyfYv3kLu6Yy5EpA)

Make sure to copy the entire url when doing so then tell me what happens then.

Thanks

**Comment by niceeeeeeeeeeeeeeeeeeeee** [comment]
it doesnt work

**Comment by VaporousCreeper** [comment]
Hi,

The only option you have left is to upload the background image to like Dropbox or Google drive and open link sharing and us said url.

Thanks.

**Comment by niceeeeeeeeeeeeeeeeeeeee** [comment]
ok i will try that

**Comment by niceeeeeeeeeeeeeeeeeeeee** [comment]
is this how it should look like?
![GGO_Kirito theme css - Visual Studio Code 2023  09  03  1_29_34](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/assets/143252588/08e4acd4-03f4-4c3c-a07a-ce650cbd354a)

**Comment by VaporousCreeper** [comment]
Hi,

Sadly, that will not work. You need a url that just the image itself.

I've already done that since you've provide the file link in the photo. Run the following url back into the variable and should work.

Image: [Background from your google drive](https://lh3.googleusercontent.com/u/0/drive-viewer/AITFw-x8MtROxZVq8zEZkBDRBKDqPfFZSBnNJxc-5I9-GGYAnhFpVjQuj1kLO_BFokxoE_XJdRdiaGMcjM61_ndvVbLgGXD20g=w1920-h955) 

Thanks

**Comment by niceeeeeeeeeeeeeeeeeeeee** [comment]
thx for all the help and sorry for all the problems, i dont really understand coding/programing

**Comment by VaporousCreeper** [comment]
All good,

That link that I've got for you will still be up till you take down the file off google drive.

Thanks.
