### ISSUE TITLE
[Bug] The theme doesn't apply well to some elements

### ISSUE THREAD

**Issue by MinatoIsuki** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#77]
In the profile:
![image](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/assets/102457568/0d6cc91f-23b5-4428-a011-efa48ba988a7)

The forum channel:
![image](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/assets/102457568/8c43427d-ac08-4c60-aa35-a038d0757386)

And Apps Directory (I swear rarely anybody uses this):
![image](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/assets/102457568/dd016ca6-c8b3-42cc-945f-8e3d672f807c)

**Comment by VaporousCreeper** [comment]
Hello MinatoIsuki,

I'm fully aware of the user popup modal for their profile and forum window not getting edited from the theme. However, I'm not aware of the app directory isn't getting edited.

I'm busy most of the time so I'll try my best to get around to it.

Thanks,
VaporousCreeper

**Comment by VaporousCreeper** [comment]
Hello Minatolsuki,

The related issues stated above has now been rectified.

Commit: [832e6a1](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/commit/832e6a1f77224b6ac1ea38619acc137d6c37acdb) 

Thanks,
VaporousCreeper
