### ISSUE TITLE
GGO_Kirito background issue

### ISSUE THREAD

**Issue by TheCommunistt** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#78]
Hi!

Just downloaded your theme (GGO_Kirito <-this one), and I noticed that the background image is just not loading.
I dont have much experience with all that (> than month experience with BDiscord moment), and I am completely bad at coding.
I'm talking about the standard (red) theme, didnt try cyan or purple yet. Before submitting the issue looked at the other issue tickets, but because, again, I'm bad at coding, so it didnt work out (maybe the solutions there aint for this issue, I dunno).

Can wait some time if needed; can speak few languages if needed. Not very active, but that sounds like me problem.
Thanks, and waiting for your reply

**Comment by VaporousCreeper** [comment]
Hello,

Please do the following.

Open up a new browser tap and click on this [link](https://images.alphacoders.com/632/632525.png).
If you can not view or download this image, then please check your firewall or similar systems that may be blocking access to the host of the image.

Thanks,
VaporousCreeper

**Comment by TheCommunistt** [comment]
Hi again,
Sorry that it took me that long to reply. After checking, I cannot access the link. Here is the saying on the page:

"**Sorry, you have been blocked**
You are unable to access alphacoders.com

**Why have I been blocked?**
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

**What can I do to resolve this?**
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page."

I checked everything that could interfere with it, found nothing.
I read all of the issue [#74 ](https://github.com/VaporousCreeper/BetterDiscord-ThemesAndPlugins/issues/74), but I didn't understand from it much. I'll reread it and let you know if I got it. For now, I will wait for your reply, and keep you informed about everything

Thanks for your time,
The Communist

**Comment by TheCommunistt** [comment]
A little update about other themes

Just figured out how to change to purple and cyan ones. From further inspecting I figured out some things:
Red (Original)- No background, can't access the site
Cyan- No background, but I can access the picture/site
Purple- Works fine, can access the picture/site

Seems like there might be a problem not only with access to the site, but with something else too.

Thanks for your time,
The Communist

**Comment by VaporousCreeper** [comment]
Hello,

It sounds like it's the host end of the image that's denying access to the image. Also to sum up what happened in issue #74 is basically downloaded the image from a different source and stored on a different location on the cloud where then BBD can use the image.

I've uploaded the images for the base theme and the templates in their respected locations for future use.

If this satisfies your issue then I'll close this issue.

Thanks,
VaporousCreeper.

**Comment by TheCommunistt** [comment]
Hi,
Everything seems to be working now. I still can't reach the red theme, but at least cyan works smoothly.
I'll leave image links here, so you will be able to fix this issue for everyone

Cyan: https://github.com/TheCommunistt/GGO_Kirito-background/blob/main/themebackgroundcyan.jpg?raw=true
Purple (just in case): https://github.com/TheCommunistt/GGO_Kirito-background/blob/main/themebackgroundpurple.jpg?raw=true

This is a repository links, so they always should work. I'll add the red one, when I'll get it

Thanks for all time spent on me,
The Communist

And remember: Nobody should know
