### ISSUE TITLE
UI boxes alignment seemed to be moved when theme is applied.

### ISSUE THREAD

**Issue by FrostyHallows** [VaporousCreeper/BetterDiscord-ThemesAndPlugins#80]
In the settings section, it seems to like to move to the far left of the screen instead of staying as it is. (Image comparison linked attached below)

![image](https://github.com/user-attachments/assets/4ceabc6f-de8d-4aad-973d-1fb049cd0667)
![image](https://github.com/user-attachments/assets/ace6c22f-881c-4cd4-aedc-79138ab2d7f4)

**Comment by VaporousCreeper** [comment]
Hello, 

This change was intentional. 

Reason being is that on the initial release (v1.0.0), it was like that can I completely forgot all about during each update since it broke.

I will now close this issue.

Thanks.
